2025-02-12 13:54:06,572 - ERROR - Could not retrieve depth information or bids/asks are empty.
2025-02-12 13:54:08,833 - ERROR - Trade Execution Error: API Secret required for private endpoints
2025-02-12 13:54:08,833 - ERROR - Error in run: cannot access local variable 'stop_loss' where it is not associated with a value
2025-02-12 13:54:08,938 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-4' coro=<ThreadedApiManager.start_listener() done, defined at C:\Python312\Lib\site-packages\binance\threaded_stream.py:44> exception=AttributeError("'ClientConnection' object has no attribute 'fail_connection'")>
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\binance\threaded_stream.py", line 45, in start_listener
    async with socket as s:
  File "C:\Python312\Lib\site-packages\binance\streams.py", line 75, in __aexit__
    self.ws.fail_connection()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'fail_connection'
2025-02-12 13:54:09,094 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-3' coro=<ThreadedApiManager.start_listener() done, defined at C:\Python312\Lib\site-packages\binance\threaded_stream.py:44> exception=AttributeError("'ClientConnection' object has no attribute 'fail_connection'")>
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\binance\threaded_stream.py", line 45, in start_listener
    async with socket as s:
  File "C:\Python312\Lib\site-packages\binance\streams.py", line 75, in __aexit__
    self.ws.fail_connection()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'fail_connection'
