2025-02-07 20:18:08,457 - ERROR - Could not retrieve depth information or bids/asks are empty.
2025-02-07 20:19:25,922 - ERROR - Error in run: 'OrderFlowAnalyzer' object has no attribute 'order_book_imbalance'
2025-02-07 20:19:25,945 - ERROR - Could not retrieve depth information or bids/asks are empty.
2025-02-07 20:19:26,063 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-4' coro=<ThreadedApiManager.start_listener() done, defined at C:\Python312\Lib\site-packages\binance\threaded_stream.py:44> exception=AttributeError("'ClientConnection' object has no attribute 'fail_connection'")>
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\binance\threaded_stream.py", line 45, in start_listener
    async with socket as s:
  File "C:\Python312\Lib\site-packages\binance\streams.py", line 75, in __aexit__
    self.ws.fail_connection()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'fail_connection'
2025-02-07 20:19:26,082 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-3' coro=<ThreadedApiManager.start_listener() done, defined at C:\Python312\Lib\site-packages\binance\threaded_stream.py:44> exception=AttributeError("'ClientConnection' object has no attribute 'fail_connection'")>
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\binance\threaded_stream.py", line 45, in start_listener
    async with socket as s:
  File "C:\Python312\Lib\site-packages\binance\streams.py", line 75, in __aexit__
    self.ws.fail_connection()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'fail_connection'
2025-02-07 20:19:46,777 - ERROR - Could not retrieve depth information or bids/asks are empty.
